language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
matrix:
    allow_failures:
        - php: hhvm
  
sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.4"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database myapp_test;'  
  - mysql -u root myapp_test < tests/data/sql/1.0.0-beta7.sql

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --configuration travis.phpunit.xml